import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTS } from './colors';

const styles = StyleSheet.create({
  // Button Styles
  adminDashboardContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 20,
  },
  superButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  questionContainer: {
    marginBottom: 20,
  },
  toggleEditorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: COLORS.addexisitng,
    borderRadius: 5,
    marginTop: 10,
  },
  addExistingButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: COLORS.switchbutton,
    borderRadius: 5,
    marginTop: 10,
    marginVertical: 15,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 20,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 4,
    alignItems: 'center',
    marginHorizontal: 5,
    marginBottom: 10,
  },
  optionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  correctButton: {
    backgroundColor: COLORS.success,
    padding: 10,
    borderRadius: 4,
    flex: 1,
    alignItems: 'center',
    marginRight: 5,
  },
  incorrectButton: {
    backgroundColor: COLORS.danger,
    padding: 10,
    borderRadius: 4,
    flex: 1,
    alignItems: 'center',
    marginRight: 5,
  },
  removeButton: {
    backgroundColor: COLORS.danger,
    padding: 10,
    borderRadius: 4,
    flex: 1,
    alignItems: 'center',
  },
  loginButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  primaryButton: {
    backgroundColor: '#007bff',
    paddingVertical: 15,
    borderRadius: 5,
    flex: 1,
    alignItems: 'center',
    marginRight: 10, // Added margin to separate the buttons
  },
  cancelButton: {
    backgroundColor: '#d9534f',
    paddingVertical: 15,
    borderRadius: 5,
    flex: 1,
    alignItems: 'center',
  },
  secondaryButton: {
    backgroundColor: COLORS.secondary,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    alignItems: 'center',
    marginRight: 10,
    marginHorizontal: 20,
    marginBottom: 16,
  },
  submitButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 4,
    alignItems: 'center',
    marginTop: 20,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: FONTS.sizeMedium,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: FONTS.sizeMedium,
    fontWeight: 'bold',
  },
  disabledButton: {
    backgroundColor: COLORS.disabled,
    marginHorizontal: 20,
    marginBottom: 16,
  },
  addButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: 5, // Adding margin between the buttons
  },
  addButtonText: {
    color: COLORS.white,
    fontSize: FONTS.sizeMedium,
    fontWeight: 'bold',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.danger,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginBottom: 20,
  },
  logoutButtonText: {
    color: COLORS.white,
    fontSize: FONTS.sizeMedium,
    fontWeight: 'bold',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: COLORS.back,
    borderRadius: 5,
    margin: 10,
    marginVertical: 10,
  },
  backButtonText: {
    color: '#fff',
    marginLeft: 10,
    fontSize: FONTS.sizeMedium,
  },
  tileButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 20,
    paddingHorizontal: 30,
    borderRadius: 10,
    justifyContent: 'center',
    width: '30%',
  },
  tileButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 10,
  },
  footerButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  footerContainer: {
    position: 'absolute',
    bottom: 20,
    width: '100%',
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: COLORS.white,
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: FONTS.sizeLarge,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  modalItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray,
    width: '100%',
  },
  userItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  userText: {
    fontSize: 18,
  },
  modalCloseButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#6200EE',
    borderRadius: 10,
  },
  modalCloseButtonText: {
    color: '#fff',
    fontSize: 18,
  },
  planActions: {
    flexDirection: 'row',
  },
  planActionButton: {
    marginLeft: 10,
  },

  // Common Styles
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    padding: 20,
  },
  centeredText: {
    textAlign: 'center',
  },
  boldText: {
    fontWeight: 'bold',
  },
  shadow: {
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  input: {
    height: 40,
    borderColor: COLORS.gray,
    borderWidth: 1,
    padding: 10,
    paddingHorizontal: 10,
    borderRadius: 4,
    backgroundColor: COLORS.white,
    marginBottom: 20,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    padding: 20,
    marginVertical: 10,
    marginHorizontal: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  editorWrapper: {
    marginBottom: 20,
    minHeight: 150,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardText: {
    flex: 1,
  },
  cardTitle: {
    fontSize: FONTS.sizeLarge,
    fontWeight: 'bold',
  },
  cardSubtitle: {
    fontSize: FONTS.sizeSmall,
    color: COLORS.textSecondary,
  },
  cardActions: {
    flexDirection: 'row',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gridItem: {
    width: '50%',
    marginBottom: 1,
  },
  option: {
    backgroundColor: '#f0f0f0',
    padding: 10,
    marginVertical: 5,
    borderRadius: 5,
  },
  flexRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  selectedOption: {
    backgroundColor: '#4caf50',
    padding: 10,
    borderRadius: 4,
    flex: 1,
    alignItems: 'center',
    marginRight: 5,
  },
  quizItem: {
    backgroundColor: COLORS.white,
    padding: 15,
    borderRadius: 8,
    marginVertical: 10,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quizText: {
    color: COLORS.textPrimary,
    fontSize: FONTS.sizeMedium,
  },

  noQuizzesText: {
    textAlign: 'center',
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  unselectedOption: {
    backgroundColor: '#f1f1f1',
    padding: 10,
    borderRadius: 4,
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  optionText: {
    fontSize: 16,
  },
  optionContainer: {
    marginBottom: 20,
  },
  questionItem: {
    marginBottom: 20,
  },
  questionText: {
    flex: 1,
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  icon: {
    marginLeft: 16,
  },
  label: {
    fontSize: FONTS.sizeMedium,
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    marginBottom: 5,
    marginLeft: 20,
  },
  planText: {
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  planAdminText: {
    fontSize: FONTS.sizeSmall,
    color: COLORS.textSecondary,
  },
  planDescriptionText: {
    fontSize: FONTS.sizeSmall,
    color: COLORS.textTertiary,
  },
  chapterText: {
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  lessonText: {
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  topicText: {
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  quizQuestion: {
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
    marginBottom: 10,
  },
  answerItem: {
    backgroundColor: COLORS.white,
    padding: 15,
    borderRadius: 8,
    marginVertical: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    flexDirection: 'column',
  },
  answerText: {
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  inputGroup: {
    marginBottom: 15,
  },
  title: {
    fontSize: FONTS.sizeLarge,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 20,
    color: COLORS.textPrimary,
  },
  subheading: {
    fontSize: FONTS.sizeMedium,
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    marginBottom: 10,
  },
  noPlansText: {
    textAlign: 'center',
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
  },
  // Header Styles
  header: {
    backgroundColor: COLORS.primary,
    padding: 5,
    alignItems: 'center',
  },
  headerText: {
    color: COLORS.white,
    fontSize: FONTS.sizeLarge,
    padding: 1,
    fontWeight: 'bold',
  },
  logoContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  welcomeText: {
    fontSize: FONTS.sizeMedium,
    textAlign: 'center',
    marginVertical: 10,
    color: COLORS.textPrimary,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
    paddingHorizontal: 20,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray,
  },
  logo: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  mainLogo: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
    marginBottom: 10,
  },
  messageContainer: {
    marginTop: 10,
    paddingHorizontal: 10,
  },
  scrollingMessage: {
    fontSize: FONTS.sizeMedium,
    color: COLORS.textPrimary,
    width: Dimensions.get('window').width - 150,
  },
  // Table and Grid Styles
  tableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray,
    marginHorizontal: 20,
  },
  tableHeaderText: {
    fontSize: FONTS.sizeMedium,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray,
    marginHorizontal: 20,
  },
  tableCell: {
    fontSize: FONTS.sizeMedium,
    flex: 1,
    textAlign: 'center',
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  
  plansList: {
    paddingHorizontal: 20,
  },
  planItem: {
    backgroundColor: COLORS.white,
    padding: 15,
    borderRadius: 8,
    marginVertical: 10,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  chapterItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray,
    marginHorizontal: 20,
  },
  lessonItem: {
    backgroundColor: COLORS.white,
    padding: 15,
    borderRadius: 8,
    marginVertical: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topicItem: {
    backgroundColor: COLORS.white,
    padding: 15,
    borderRadius: 8,
    marginVertical: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quizItem: {
    backgroundColor: COLORS.white,
    padding: 15,
    borderRadius: 8,
    marginVertical: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});


export default styles;

